# Generated by Django 2.1.5 on 2019-02-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'street',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Street'),
        ),
    ]
