# Generated by Django 2.1.5 on 2019-02-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
